// <auto-generated />
namespace CRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_lead_developer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_lead_developer));
        
        string IMigrationMetadata.Id
        {
            get { return "202112300139277_add_lead_developer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
